version = "1.0"

[metadata]
[environment]
build_timeout_sec = 600
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
POCHI_LOG = "debug"
POCHI_API_KEY = "${POCHI_API_KEY}"
CH_API_KEY_ID = "${CLICKHOUSE_KEY_ID}"
CH_API_KEY_SECRET = "${CLICKHOUSE_KEY_SECRET}"
CH_ORG_ID = "${CLICKHOUSE_ORG_ID}"
CH_SERVICE_ID = "${CLICKHOUSE_SERVICE_ID}"

[agent]
timeout_sec = 600

[verifier]
timeout_sec = 600

[verifier.env]
POCHI_LOG = "debug"
POCHI_API_KEY = "${POCHI_API_KEY}"
CH_API_KEY_ID = "${CLICKHOUSE_KEY_ID}"
CH_API_KEY_SECRET = "${CLICKHOUSE_KEY_SECRET}"
CH_ORG_ID = "${CLICKHOUSE_ORG_ID}"
CH_SERVICE_ID = "${CLICKHOUSE_SERVICE_ID}"

[solution.env]
